repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.2
    hooks:
      - id: go-fmt-import
      - id: go-vet
      - id: go-lint
